### PR TITLE
Added a sandwich favicon

### PR DESCRIPTION
**Pull request by paymog**
See title

### CODE REVIEW

**Comment by kjrcda** [comment]
Where do we see this?

**Comment by kjrcda** [comment]
I can't see it in firefox for some reason. However it shows up in IE

**Comment by paymog** [comment]
Odd...it works for me.

What happens if you navigate to `localhost:3000/favicon.ico` in firefox?

**Comment by kyleleung75** [comment]
It looks good for me on both chrome and IE

**Comment by kjrcda** [comment]
late comment, works in firefox too

**Pull request merged**
