### PR TITLE
Added min value restrictions to age and radius

### LINKED ISSUE #57: Can enter negative values for age and radius when registering

### PR DESCRIPTION
**Pull request by paymog**
Fixes #57

### CODE REVIEW

**Comment by kyleleung75** [comment]
Tested this one out and it looks good!

**Comment by BrandonWade** [comment]
This seems pretty straightforward. Looks good.

**Comment by paymog** [comment]
Don't need the regex: https://docs.angularjs.org/api/ng/input/input%5Bemail%5D

**Comment by BrandonWade** [comment]
This fixes both the email and minimum value issues.

**Pull request merged**
